name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  windows_msvc_x64_benchmarks:
    name: Windows MSVC x64 Benchmark
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x64_compile_and_run_benchmark.bat

  windows_msvc_x64_tests:
    name: Windows MSVC x64 Tests
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x64_compile_and_run_tests.bat

  windows_msvc_x86_benchmarks:
    name: Windows MSVC x86 Benchmark
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x86_compile_and_run_benchmark.bat

  windows_msvc_x86_tests:
    name: Windows MSVC x86 Tests
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x86_compile_and_run_tests.bat

  windows_msvc_arm64_benchmarks:
    name: Windows MSVC ARM64 Benchmark
    runs-on: windows-11-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_arm64_compile_and_run_benchmark.bat

  windows_msvc_arm64_tests:
    name: Windows MSVC ARM64 Tests
    runs-on: windows-11-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_arm64_compile_and_run_tests.bat

  linux_gcc_x64_benchmarks:
    name: Linux GCC x64 Benchmark
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/gcc_x64_compile_and_run_benchmark.sh

  linux_gcc_x64_tests:
    name: Linux GCC x64 Tests
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: ash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/gcc_x64_compile_and_run_tests.bat

  linux_gcc_x86_benchmarks:
    name: Linux GCC x86 Benchmark
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: ash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/gcc_x86_compile_and_run_benchmark.bat

  linux_gcc_x86_tests:
    name: Linux GCC x86 Tests
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: ash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/gcc_x86_compile_and_run_tests.bat