name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  # ---------------------------------------------------------------------------------------------------------------------
  windows_msvc_x64_benchmarks:
    name: Windows MSVC x64 Benchmark
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x64_compile_and_run_benchmark.bat

  windows_msvc_x64_tests:
    name: Windows MSVC x64 Tests
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x64_compile_and_run_tests.bat

  windows_msvc_x86_benchmarks:
    name: Windows MSVC x86 Benchmark
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x86_compile_and_run_benchmark.bat

  windows_msvc_x86_tests:
    name: Windows MSVC x86 Tests
    runs-on: windows-2022
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_x86_compile_and_run_tests.bat

  windows_msvc_arm64_benchmarks:
    name: Windows MSVC ARM64 Benchmark
    runs-on: windows-11-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_arm64_compile_and_run_benchmark.bat

  windows_msvc_arm64_tests:
    name: Windows MSVC ARM64 Tests
    runs-on: windows-11-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      shell: cmd 
      working-directory: ${{github.workspace}}/projects/scripts
      run: ${{github.workspace}}/projects/scripts/msvc_arm64_compile_and_run_tests.bat

  # ---------------------------------------------------------------------------------------------------------------------
  linux_gcc_x64_benchmarks:
    name: Linux GCC x64 Benchmark
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/gcc_x64_compile_and_run_benchmark.sh

  linux_gcc_x64_tests:
    name: Linux GCC x64 Tests
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/gcc_x64_compile_and_run_tests.sh

  linux_gcc_x86_benchmarks:
    name: Linux GCC x86 Benchmark
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Install gcc-multilib
      run: sudo apt install -y gcc-multilib
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/gcc_x86_compile_and_run_benchmark.sh

  linux_gcc_x86_tests:
    name: Linux GCC x86 Tests
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Install gcc-multilib
      run: sudo apt install -y gcc-multilib
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/gcc_x86_compile_and_run_tests.sh
  
  linux_gcc_arm64_benchmarks:
    name: Linux GCC ARM64 Benchmark
    runs-on: ubuntu-26.04-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/gcc_arm64_compile_and_run_benchmark.sh

  linux_gcc_arm64_tests:
    name: Linux GCC ARM64 Tests
    runs-on: ubuntu-26.04-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/gcc_arm64_compile_and_run_tests.sh

  # ---------------------------------------------------------------------------------------------------------------------
  linux_clang_x64_benchmarks:
    name: Linux Clang x64 Benchmark
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/clang_x64_compile_and_run_benchmark.sh

  linux_clang_x64_tests:
    name: Linux Clang x64 Tests
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/clang_x64_compile_and_run_tests.sh

  linux_clang_x86_benchmarks:
    name: Linux Clang x86 Benchmark
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Install clang-multilib
      run: sudo apt-get install libc6-dev-i386-cross
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/clang_x86_compile_and_run_benchmark.sh

  linux_clang_x86_tests:
    name: Linux Clang x86 Tests
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Install clang-multilib
      run: sudo apt-get install libc6-dev-i386-cross
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/clang_x86_compile_and_run_tests.sh
  
  linux_clang_arm64_benchmarks:
    name: Linux Clang ARM64 Benchmark
    runs-on: ubuntu-26.04-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/clang_arm64_compile_and_run_benchmark.sh

  linux_clang_arm64_tests:
    name: Linux Clang ARM64 Tests
    runs-on: ubuntu-26.04-arm
    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
    - name: Build
      shell: bash 
      working-directory: ${{github.workspace}}/projects/scripts
      run: bash ${{github.workspace}}/projects/scripts/clang_arm64_compile_and_run_tests.sh